# Generated by Django 3.2.25 on 2024-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(help_text='Nome do funcionário com o aparelho', max_length=100)),
                ('imei', models.CharField(help_text='Número IMEI do aparelho', max_length=15, unique=True)),
                ('numero_cadastrado', models.CharField(help_text='Número de telefone cadastrado no aparelho', max_length=15)),
                ('nome_dispositivo', models.CharField(help_text='Nome ou modelo do dispositivo', max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True, help_text='Data de registro')),
            ],
        ),
    ]
