# Generated by Django 3.2.25 on 2024-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelho',
            name='imei_e_sim',
            field=models.CharField(help_text='Número IMEI(eSIM) do aparelho', max_length=15, null=True, unique=True),
        ),
    ]
